package com.alihaine.bulmultiverse.message;

public enum MessageType {
    NO_WORLD_TARGET,
    WORLD_NOT_FOUND,
    FLAG_NOT_FOUND,
    FORBIDDEN_WORLD_NAME,
    CMD_LOAD_SUCCESS,
    CMD_TELEPORT_SUCCESS,
    CMD_UNLOAD_SUCCESS,
    ERROR_SET_OPTION,
    ERROR_WORLD_CREATOR,
    HELP_PATTERN,
    FLAGS_PATTERN,
    ONLY_INGAME_COMMAND,
    NO_PERMISSION;
}
